CREATE DATABASE IF NOT EXISTS board01;
GRANT SELECT, INSERT, UPDATE, DELETE ON board01.* TO board_root@localhost IDENTIFIED BY 'board_root';
FLUSH PRIVILEGES;

Use board01;
CREATE TABLE IF NOT EXISTS thread01 (
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
    )ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comment01 (
    id INT(11) NOT NULL AUTO_INCREMENT,
    thread_id INT(11) NOT NULL,
    username VARCHAR(20) NOT NULL,
    body VARCHAR(140) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX (thread_id, created)
    )ENGINE=InnoDB;








